spring:
  datasource:
    username: root
    password: lw1937553971
    url: jdbc:mysql://localhost:3306/testdb?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.maple.bean
  mapper-locations: classpath:mapper/*.xml
